# Site settings
title: Trevor Bernard
email: trevor.bernard@gmail.com
author: Trevor Bernard
description: "Software consulting services; Product development; Technical Leadership; Bespoke software."
baseurl: ""
url: "http://trevorbernard.com"
google_analytics: UA-17847179-1
animated: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
sass:
  compressed: true
